### ISSUE TITLE
Download site returns 404

### ISSUE THREAD

**Issue by stevenjgilmore** [vmtk/vmtk.github.com#3]
Hi,

I am getting this error when attempting to download with homebrew. I have successfully installed vmtk on other machines using this process. 

```
> brew install https://raw.githubusercontent.com/vmtk/vmtk/master/distribution/homebrew/vmtk.rb

curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing: /usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.0\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.12)\ curl/7.49.1 --progress-bar --fail https://raw.githubusercontent.com/vmtk/vmtk/master/distribution/homebrew/vmtk.rb -o /var/.home/admin/Library/Caches/Homebrew/Formula/vmtk.rb
```
Any advice is much appreciated. Thanks!

**Comment by lantiga** [comment]
The documentation has now been fixed: the correct path to the file has been changed to `https://raw.githubusercontent.com/vmtk/vmtk/v1.3.2/distribution/homebrew/vmtk.rb`
Thank you for reporting this.
